name: Apptainer Build Deploy

on:
  pull_request:
  push:
    branches: main

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: quay.io/singularity/singularity:v4.1.0
        options: --privileged

    name: Build Container
    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v4

      - name: Pull Container
        run: |
           singularity pull nothingtoseehere.sif docker://ghcr.io/${{ github.repository_owner }}/nothingtoseehere:latest
      
      - name: Login and Deploy Container
        run: |
           -echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ github.repository_owner }} --password-stdin oras://ghcr.io
           